apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: second-pvc
  namespace: bankapp-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual

